# Generated by Django 6.0.5 on 2026-06-02 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '__first__'),
        ('inventario', '0006_rename_produccion_fecha_and_fecha_vencimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_producto', 'Stock Producto'), ('stock_ingrediente', 'Stock Ingrediente'), ('vencimiento_producto', 'Vencimiento Producto'), ('deuda_vencida', 'Deuda Vencida'), ('deuda_proxima', 'Deuda Próxima')], max_length=30)),
                ('mensaje', models.TextField(blank=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creditos.credito')),
                ('cuota_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creditos.cuotacredito')),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.ingrediente')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha_generada'],
            },
        ),
    ]
