# Generated by Django 6.0.5 on 2026-05-21 18:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('stock_actual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml')], max_length=3)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'ingrediente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_actual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('inhabilitado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('AJUSTE', 'AJUSTE')], max_length=10)),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_posterior', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ingrediente')),
            ],
            options={
                'verbose_name': 'Movimiento_Ingrediente',
                'verbose_name_plural': 'Movimientos_Ingredientes',
                'db_table': 'movimiento_ingrediente',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('AJUSTE', 'AJUSTE')], max_length=10)),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_posterior', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento_Producto',
                'verbose_name_plural': 'Movimientos_Productos',
                'db_table': 'movimiento_producto',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_ingrediente', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ingrediente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto_Ingrediente',
                'verbose_name_plural': 'Productos_Ingredientes',
                'db_table': 'producto_ingrediente',
                'ordering': ['id'],
            },
        ),
    ]
