# Generated by Django 6.0.5 on 2026-05-21 04:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('proveedor', models.TextField()),
                ('stock_actual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('ml', 'ml')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_actual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('inhabilitado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('AJUSTE', 'AJUSTE')], max_length=10)),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_posterior', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producida', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA'), ('AJUSTE', 'AJUSTE')], max_length=10)),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_posterior', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoIngrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_ingrediente', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ingrediente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventario.producto')),
            ],
        ),
    ]
