# Generated by Django 6.0.5 on 2026-05-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(related_name='productos', through='inventario.ProductoIngrediente', to='inventario.ingrediente'),
        ),
        migrations.AddField(
            model_name='productoingrediente',
            name='cantidad_ingrediente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoingrediente',
            name='cantidad_producida',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productoingrediente',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='productoingrediente',
            name='porcentaje_ingrediente',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
