# Generated by Django 6.0.5 on 2026-06-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
