# Generated by Django 6.0.5 on 2026-06-02 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0002_remove_pedido_pago_presencial_requerido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.SmallIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frecuencia_dias', models.PositiveSmallIntegerField(default=30, help_text='Días entre cada cuota. Ej: 30 = mensual, 15 = quincenal.')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='activo', max_length=10)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credito',
            },
        ),
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.SmallIntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('valor_cuota_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incremento_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_cuota_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_interes', models.DateTimeField(blank=True, help_text='Marca hasta qué período se calculó el interés. Se inicializa con fecha_vencimiento y avanza período a período.', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('parcial', 'Parcial')], default='pendiente', max_length=10)),
                ('notificaciones_activas', models.BooleanField(default=True, help_text='Si False, no se generan notificaciones para esta cuota.')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='creditos.credito')),
            ],
            options={
                'db_table': 'cuota_credito',
                'ordering': ['numero_cuota'],
            },
        ),
    ]
