# Generated by Django 6.0.5 on 2026-05-22 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0002_remove_carritodecompras_producto_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.SmallIntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='activo', max_length=10)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credito',
            },
        ),
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.SmallIntegerField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('valor_cuota_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incremento_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_cuota_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('parcial', 'Parcial')], default='pendiente', max_length=10)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='creditos.credito')),
            ],
            options={
                'db_table': 'cuota_credito',
            },
        ),
    ]
