# Generated by Django 6.0.5 on 2026-06-02 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_rename_produccion_fecha_and_fecha_vencimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('checkout', 'Checkout'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('usuario', models.OneToOneField(help_text='Usuario/Cliente al que pertenece el carrito', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito de Compras',
                'verbose_name_plural': 'Carritos de Compras',
                'db_table': 'carrito_compras',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('billetera_digital', 'Billetera_digital'), ('efectivo', 'Efectivo'), ('credito', 'Credito')], max_length=20)),
                ('cliente_presencial', models.BooleanField(default=False)),
                ('coordenadas_lat', models.FloatField(blank=True, null=True)),
                ('coordenadas_lng', models.FloatField(blank=True, null=True)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], max_length=20)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('id_transaccion_wompi', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_pago', models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Pedido Producto',
                'db_table': 'pedido_producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('carrito_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.carritocompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto carrito',
                'db_table': 'producto_carrito',
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_pago__in', ['efectivo', 'credito']), _negated=True), ('cliente_presencial', True), _connector='OR'), name='pago_presencial_requerido'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('precio_total__gt', 0)), name='precio_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('costo_envio__gte', 0)), name='costo_envio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproducto',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='unique_pedido_producto'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproducto',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_positiva_pedido'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='precio_unitario_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pedidoproducto',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gt', 0)), name='subtotal_positivo'),
        ),
        migrations.AddConstraint(
            model_name='productocarrito',
            constraint=models.UniqueConstraint(fields=('producto', 'carrito_compra'), name='unique_producto_carrito'),
        ),
        migrations.AddConstraint(
            model_name='productocarrito',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_positiva_carrito'),
        ),
    ]
