# Generated by Django 6.0.5 on 2026-06-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobado_admin',
            field=models.BooleanField(default=False, help_text='True cuando el administrador revisó el pedido y definió el envío. Requerido para habilitar el pago online.'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_wompi',
            field=models.CharField(blank=True, help_text='Referencia única enviada a Wompi (PEDIDO-{id}-{token}).', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carritocompra',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('checkout', 'Checkout'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
