# Generated by Django 6.0.5 on 2026-05-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritodecompras',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='carritodecompras',
            name='producto',
            field=models.ForeignKey(default=1, help_text='Producto en el carrito', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(default=1, help_text='Producto del pedido', on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
            preserve_default=False,
        ),
    ]
