# Generated by Django 6.0.5 on 2026-06-02 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='pago_presencial_requerido',
        ),
        migrations.RemoveConstraint(
            model_name='pedido',
            name='costo_envio_no_negativo',
        ),
        migrations.RemoveField(
            model_name='carritocompra',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='medio_pago',
            field=models.TextField(blank=True, help_text='Detalle del método reportado por Wompi (p. ej. CARD, NEQUI).', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('wompi', 'Wompi'), ('efectivo', 'Efectivo'), ('credito', 'Credito')], help_text='En pedidos web lo asigna el webhook de Wompi al aprobar.', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_pago__isnull', True), models.Q(('tipo_pago__in', ['efectivo', 'credito']), _negated=True), ('cliente_presencial', True), _connector='OR'), name='pago_presencial_requerido'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='aprobado_admin',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='coordenadas_lat',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='coordenadas_lng',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='costo_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado_pedido',
        ),
    ]
