# Generated by Django 6.0.5 on 2026-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_pedido_pago_presencial_requerido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('wompi', 'Wompi'), ('contado', 'Contado'), ('credito', 'Credito')], help_text='En pedidos web lo asigna el webhook de Wompi al aprobar.', max_length=20, null=True),
        ),
    ]
