# Generated by Django 6.0.5 on 2026-06-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_pedido_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
